const Data=[
    {
        name:"HTML-5",
        src:"https://img.freepik.com/free-icon/html5_318-903450.jpg",
        key:1
    },
    {
        name:"CSS3",
        src:"https://cdn.worldvectorlogo.com/logos/css-3.svg",
        key:2
    },
    {
        name:"Javascript",
        src:"https://cdn.worldvectorlogo.com/logos/logo-javascript.svg",
        key:3
    },
    {
        name:"C",
        src:"https://upload.wikimedia.org/wikipedia/commons/1/18/C_Programming_Language.svg",
        key:4
    },
    {
        name:"C++",
        src:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/ISO_C%2B%2B_Logo.svg/1822px-ISO_C%2B%2B_Logo.svg.png",
        key:5
    },
    {
        name:"React",
        src:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png",
        key:6
    },
    {
        name:"MySQL",
        src:"https://www.svgrepo.com/show/303251/mysql-logo.svg",
        key:7
    },
    {
        name:"Git",
        src:"https://git-scm.com/images/logos/downloads/Git-Icon-1788C.png",
        key:8
    },
    {
        name:"Sass",
        src:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Sass_Logo_Color.svg/1280px-Sass_Logo_Color.svg.png",
        key:9
    },
    {
        name:"Java",
        src:"https://i.pinimg.com/originals/79/5e/bb/795ebb5f4a470cd7242136237f61fc53.png",
        key:10
    }
];

export default Data;